version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
      time: "07:00"
  - package-ecosystem: docker
    directory: "containers/elasticsearch"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    target-branch: main
    reviewers:
      - nlx-sascha
      - phroust
      - liwo
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "containers/mariadb"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    target-branch: main
    reviewers:
      - nlx-sascha
      - phroust
      - liwo
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "containers/proxy"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    target-branch: main
    reviewers:
      - nlx-sascha
      - phroust
      - liwo
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "containers/rabbitmq"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    target-branch: main
    reviewers:
      - nlx-sascha
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "containers/redis"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    target-branch: main
    reviewers:
      - nlx-sascha
      - phroust
      - liwo
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "containers/styleguide"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    target-branch: main
    reviewers:
      - nlx-sascha
      - phroust
      - liwo
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "containers/varnish"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    target-branch: main
    reviewers:
      - nlx-sascha
      - phroust
      - liwo
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "containers/webserver"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    target-branch: main
    reviewers:
      - nlx-sascha
      - phroust
      - liwo
    labels:
      - dependencies
