server_tokens off;

map $http_x_forwarded_proto $ws_scheme {
    default "ws";
    https   "wss";
}

server {
    listen 9222;

    location = / {
        root /var/lib/nginx/www;
        try_files /index.html /index.html;
    }

    location /devtools/ {
        proxy_http_version 1.1;

        proxy_set_header Host 127.0.0.1:9221;
        proxy_pass http://127.0.0.1:9221;

        proxy_set_header Upgrade "websocket";
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 86400;
    }

    location /serve_rev/ {
        proxy_pass https://chrome-devtools-frontend.appspot.com;
        proxy_ssl_server_name on;
    }

    location / {
        proxy_http_version 1.1;

        proxy_set_header Host 127.0.0.1:9221;
        proxy_pass http://127.0.0.1:9221;

        sub_filter_once off;
        sub_filter_types application/json;

        sub_filter "ws=127.0.0.1:9221" "$ws_scheme=$http_host";
        sub_filter "ws://127.0.0.1:9221" "$ws_scheme://$http_host";
        sub_filter "https://chrome-devtools-frontend.appspot.com/serve_rev" "$http_x_forwarded_proto://$http_host/serve_rev";
    }
}
