#!/bin/sh
set -e

# this will check if the first argument is a flag
# but only works if all arguments require a hyphenated flag
# -v; -SL; -f arg; etc will work, but not arg1 arg2
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
    set -- varnishd \
      -F \
      -f /etc/varnish/default.vcl \
      -a http=:${VARNISH_HTTP_PORT:-80},HTTP \
      -a proxy=:${VARNISH_PROXY_PORT:-8443},PROXY \
      -p feature=+http2 \
      -s malloc,${VARNISH_SIZE:-500m} \
      -s secondary=file,/tmp,${VARNISH_STORAGE_SIZE:-1G} \
      -t 120 \
      -p thread_pools=1 \
      -p thread_pool_add_delay=2 \
      -p thread_pool_min=5 \
      -p thread_pool_max=500 \
      -p thread_pool_timeout=300 \
      "$@"
fi

exec "$@"
