#!/bin/sh
set -e

env > /etc/environment

CRONTAB_PATH="${CRONTAB_PATH:-/var/www/Configuration/crontab}"

# init crontab file
if [ -f $CRONTAB_PATH ]; then
    crontab -u $CRON_USER - < $CRONTAB_PATH
fi

exec "$@"
