#!/bin/sh
set -e

export VHOST_PATH="/var/www"
env > /etc/environment

CRONTAB_PATH="${CRONTAB_PATH:-/var/www/Configuration/crontab}"
CRON_USER="${CRON_USER:-www-data}"

# init crontab file
if [ -f $CRONTAB_PATH ]; then
    crontab -u $CRON_USER - < $CRONTAB_PATH
fi

exec "$@"
