name: 'Build mariadb docker image'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: 0 7 * * THU
  push:
    branches:
      - main
    paths:
      - mariadb/**
  pull_request:
    branches:
      - main
    paths:
      - mariadb/**
  workflow_dispatch:
    inputs: {}

jobs:
  build-docker-image:
    name: 'Build mariadb-${{ matrix.image.version }} docker image'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        image:
          - version: 10.6
            file: 10.6.Dockerfile
          - version: 10.11
            file: 10.11.Dockerfile
          - version: latest
            file: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (mariadb)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./mariadb
          target: mariadb
          file: ./mariadb/${{ matrix.image.file || 'Dockerfile' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/netlogix/docker/mariadb:${{ matrix.image.version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha, scope=${{ github.workflow }}-mariadb
          cache-to: type=gha, scope=${{ github.workflow }}-mariadb, mode=max

