name: 'Build postgres docker image'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: 0 7 * * THU
  push:
    branches:
      - main
    paths:
      - postgres/**
      - .github/workflows/postgres.yml
  pull_request:
    branches:
      - main
    paths:
      - postgres/**
      - .github/workflows/postgres.yml
  workflow_dispatch:
    inputs: {}

jobs:
  build-docker-image:
    name: 'Build postgres-${{ matrix.image.version }} docker image'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        image:
          - file: 12.Dockerfile
          - file: 14.Dockerfile
          - file: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read version from Dockerfile
        id: docker
        run: echo "version=$(./extract-version.sh ./postgres/${{ matrix.image.file || 'Dockerfile' }})" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (postgres)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./postgres
          target: postgres
          file: ./postgres/${{ matrix.image.file || 'Dockerfile' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/netlogix/docker/postgres:${{ steps.docker.outputs.version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha, scope=${{ github.workflow }}-postgres
          cache-to: type=gha, scope=${{ github.workflow }}-postgres, mode=max

