name: 'Build prometheus-apache-exporter docker image'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: 0 7 * * THU
  push:
    branches:
      - main
    paths:
      - prometheus-apache-exporter/**
  pull_request:
    branches:
      - main
    paths:
      - prometheus-apache-exporter/**
  workflow_dispatch:
    inputs: {}

jobs:
  build-docker-image:
    name: 'Build prometheus-apache-exporter docker image'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (prometheus-apache-exporter)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./prometheus-apache-exporter
          target: prometheus-apache-exporter
          file: ./prometheus-apache-exporter/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/netlogix/docker/prometheus-apache-exporter:latest,ghcr.io/netlogix/docker/prometheus-apache-exporter:1.0.8
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha, mode=max

